package math_.Math;

/**
* math_/Math/AdderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adder.idl
* Friday, 2 February, 2024 9:45:33 PM IST
*/

public final class AdderHolder implements org.omg.CORBA.portable.Streamable
{
  public math_.Math.Adder value = null;

  public AdderHolder ()
  {
  }

  public AdderHolder (math_.Math.Adder initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = math_.Math.AdderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    math_.Math.AdderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return math_.Math.AdderHelper.type ();
  }

}
