package math_.Math;


/**
* math_/Math/AdderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adder.idl
* Friday, 2 February, 2024 9:45:33 PM IST
*/

public interface AdderOperations 
{
  int add (int a, int b);
} // interface AdderOperations
