package math_.Math;


/**
* math_/Math/Adder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adder.idl
* Friday, 2 February, 2024 9:45:33 PM IST
*/

public interface Adder extends AdderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Adder
