package math_.Math;


/**
* math_/Math/AdderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Adder.idl
* Friday, 2 February, 2024 9:45:33 PM IST
*/

abstract public class AdderHelper
{
  private static String  _id = "IDL:Math/Adder:1.0";

  public static void insert (org.omg.CORBA.Any a, math_.Math.Adder that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static math_.Math.Adder extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (math_.Math.AdderHelper.id (), "Adder");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static math_.Math.Adder read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, math_.Math.Adder value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static math_.Math.Adder narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof math_.Math.Adder)
      return (math_.Math.Adder)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      math_.Math._AdderStub stub = new math_.Math._AdderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static math_.Math.Adder unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof math_.Math.Adder)
      return (math_.Math.Adder)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      math_.Math._AdderStub stub = new math_.Math._AdderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
